name: Test Suite

on:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  tests-with-cache-on-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run Hardhat Tests
        id: testing
        run: bash .github/scripts/testing.sh
      - name: Read test_output.log
        id: test_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test_output.log
      - uses: actions/github-script@0.9.0
        env:
          OUTPUT_TESTS: ${{ steps.test_output.outputs.content }}
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { OUTPUT_TESTS} = process.env;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: OUTPUT_TESTS
            })
      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
          threshold_metric: "lines"